apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mms-sklearn
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: s3Key
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://models-testing/sklearn/1.0/model