apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mms-sklearn"
spec:
  predictor:
    serviceAccountName: s3sa
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://models-testing/sklearn/1.0/model"